name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@test-packages-erosoft'

      # Instala dependências, incluindo o Turborepo
      - run: npm install

      # Constrói cada pacote usando Turborepo
      - run: npx turbo run build

      # Publica cada pacote individualmente
      - name: Publish each package
        run: |
          for dir in ./packages/*; do
            if [ -d "$dir" ]; then
              cd "$dir"
              npm publish --access public
              cd ../..
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
